function [sturct_of_images] = ...
    Tapering_and_area(sturct_of_images)
%Generates the tapering meausrement and the crossection measurment

%We need to compute each tapering measurment indivdually
for i = 1:length(sturct_of_images.tapering_images_array)
    
    %Need to get the parameteres frmo the ray casting
    plane_input_sturct = ...
        Return_airway_interpol_para(sturct_of_images.raw_header);
    
    %Need to compute the cross sectional area
    area_results = ...
        Computing_lumen_FWHM_SL_with_safety_catch(...
        sturct_of_images.tapering_images_array(i).tapering_raw_image.resample_image,...
        plane_input_sturct,...
        sturct_of_images.tapering_images_array(i).tapering_seg_image.resample_image);
    
    %Need to compute the tapering measurment
    area_results.tapering = ...
        Log_taper_rate_of_ordered_array(...
        sturct_of_images.tapering_images_array(i).tapering_raw_image.arclegth,...
        area_results.phyiscal_area);
    
    %Need to combine them with the tapering array
    sturct_of_images.tapering_images_array(i).tapering_raw_image.area_results = ...
        area_results;
    
    
end
end

